version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - project-network
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-rabbitmq
        target: /var/lib/rabbitmq

  gateway:
    build: apiGateway/.
    image: project-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - project-network
    environment:
      - USER_HOST=user
      - USER_PORT=8080

  db-user:
    container_name: db-user
    image: "postgres"
    networks:
      - project-network
    environment:
      POSTGRES_DB: project-user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-db-user
        target: /data
        volume:
          nocopy: true

  user:
    build: user/.
    image: project-user
    container_name: prog-user_c
    environment:
      POSTGRES_DB_HOST: db-user
      API_GATEWAY_HOST: api-gateway
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db-user
      - rabbitmq
    networks:
      - project-network

networks:
  project-network:

volumes:
  data-db-user:
  data-rabbitmq:


# docker-compose build && docker-compose up
