version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - project-network
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-rabbitmq
        target: /var/lib/rabbitmq

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#      PGADMIN_LISTEN_PORT: 50
#    ports:
#      - "5050:50"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    depends_on:
#      - db-catalog
#      - db-user
#      - db-reservation
#    networks:
#      - project-network

  gateway:
    build: apiGateway/.
    image: project-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - project-network
    environment:
      - USER_HOST=user
      - USER_PORT=8080
      - CATALOG_HOST=catalog
      - CATALOG_PORT=8080
      - RESERVATION_HOST=reservation
      - RESERVATION_PORT=8080
      - REVIEW_HOST=review
      - REVIEW_PORT=8080

  db-catalog:
    container_name: db-catalog
    image: "postgres"
    networks:
      - project-network
    environment:
      POSTGRES_DB: project-catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-db-catalog
        target: /data
        volume:
          nocopy: true
  
  catalog:
    build: catalog/.
    image: project-catalog
    container_name: prog-catalog_c
    environment:
      POSTGRES_DB_HOST: db-catalog
      API_GATEWAY_HOST: api-gateway
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db-catalog
      - rabbitmq
    networks:
      - project-network
          
  db-user:
    container_name: db-user
    image: "postgres"
    networks:
      - project-network
    environment:
      POSTGRES_DB: project-user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-db-user
        target: /data
        volume:
          nocopy: true

  user:
    build: user/.
    image: project-user
    container_name: prog-user_c
    environment:
      POSTGRES_DB_HOST: db-user
      API_GATEWAY_HOST: api-gateway
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db-user
      - rabbitmq
    networks:
      - project-network

  db-reservation:
    container_name: db-reservation
    image: "postgres"
    networks:
      - project-network
    environment:
      POSTGRES_DB: project-reservation
      POSTGRES_USER: reservation
      POSTGRES_PASSWORD: reservation
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-db-reservation
        target: /data
        volume:
          nocopy: true

  reservation:
    build: reservation/.
    image: project-reservation
    container_name: prog-reservation_c
    environment:
      POSTGRES_DB_HOST: db-reservation
      API_GATEWAY_HOST: api-gateway
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db-reservation
      - rabbitmq
    networks:
      - project-network

  db-review:
    container_name: db-review
    image: "postgres"
    networks:
      - project-network
    environment:
      POSTGRES_DB: project-review
      POSTGRES_USER: review
      POSTGRES_PASSWORD: review
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-db-review
        target: /data
        volume:
          nocopy: true

  review:
    build: review/.
    image: project-review
    container_name: prog-review_c
    environment:
      POSTGRES_DB_HOST: db-review
      API_GATEWAY_HOST: api-gateway
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db-review
      - rabbitmq
    networks:
      - project-network


networks:
  project-network:

volumes:
  data-db-user:
  data-db-catalog:
  data-db-reservation:
  data-db-review:
  data-rabbitmq:
  pgadmin-data:


# docker-compose build && docker-compose up
