version: '3'

services:
  dbpostgresql:
    image: "postgres"
    container_name: postgres
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appbootrestnet
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  app:
    build: .
    image: booktest
    container_name: booktest
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    networks:
      - appbootrestnet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/bookdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  db-data:
  pgadmin-data:
networks:
  appbootrestnet:
    driver: bridge
# docker-compose build && docker-compose up

